### ISSUE TITLE
Polykey-Docs: Non-Clickable Sidebar Category in Docusaurus Documentation

### ISSUE THREAD

**Issue by CryptoTotalWar** [MatrixAI/Polykey-Docs#91]
# Requirements to close ticket

- [X] Achieve desired effect for getting started sidebar's structure
- [x] Update the gtag implementation referencing the latest directory name structures correctly
  - I investigated and was unable to find the cause of the issue to fix. A bug report is being made for this. 

## Is your feature request related to a problem? Please describe.

In the current setup of our Docusaurus-based documentation site, we face a limitation where categories in the sidebar are expected to link to a document or an automatically generated index page. This behavior necessitates that each category, including "Tutorials," is clickable and leads to a specific page. However, our design and user experience goals require the "Tutorials" category to solely act as a navigational container for its sub-pages without being linked to its own page. Attempts to remove the link or associate it with a README have led to build errors, indicating Docusaurus expects a document for navigation purposes.

## Describe the solution you'd like

We aim to modify the sidebar behavior so that the "Tutorials" category remains visible and expandable/collapsible, allowing access to its sub-pages, but does not navigate to a separate page when clicked. Essentially, clicking on "Tutorials" should not redirect users but merely serve as a label for the subsections listed beneath it.

### Target Behavior

![image](https://uploads.linear.app/e2a70dcf-d4d4-49a0-8551-1f7b7c87efa2/2953e7c7-7b8a-4082-a932-be33db28ed51/b97e8922-e085-4c0e-8bb8-76cd3d2c4a88?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2UyYTcwZGNmLWQ0ZDQtNDlhMC04NTUxLTFmN2I3Yzg3ZWZhMi8yOTUzZTdjNy03YjhhLTQwODItYTkzMi1iZTMzZGIyOGVkNTEvYjk3ZTg5MjItZTA4NS00YzBlLThiYjgtNzZjZDNkMmM0YTg4IiwiaWF0IjoxNzIwODA0MzU5LCJleHAiOjMzMjkxMzY0MzU5fQ.13QvlQAWDSI1tha2k4T4KQeXhedJMq2seHKoSyGfpIc "=265x")

![image](https://uploads.linear.app/e2a70dcf-d4d4-49a0-8551-1f7b7c87efa2/3d4df386-7933-434e-a109-2ab3b6687eab/6e9847ac-ced3-4c1a-a19b-80bde06dce00?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2UyYTcwZGNmLWQ0ZDQtNDlhMC04NTUxLTFmN2I3Yzg3ZWZhMi8zZDRkZjM4Ni03OTMzLTQzNGUtYTEwOS0yYWIzYjY2ODdlYWIvNmU5ODQ3YWMtY2VkMy00YzFhLWExOWItODBiZGUwNmRjZTAwIiwiaWF0IjoxNzIwODA0MzU5LCJleHAiOjMzMjkxMzY0MzU5fQ.5kGrFT2Ad4hMurQ3aTynqceZG82uWyycaBPtpgzYkXw "=492x")

### Current behavior

![image](https://uploads.linear.app/e2a70dcf-d4d4-49a0-8551-1f7b7c87efa2/43c52f5a-a665-48c9-b2c9-7d8fcc693287/2f79bb47-38a8-4176-bf36-8cb0c7ac4980?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2UyYTcwZGNmLWQ0ZDQtNDlhMC04NTUxLTFmN2I3Yzg3ZWZhMi80M2M1MmY1YS1hNjY1LTQ4YzktYjJjOS03ZDhmY2M2OTMyODcvMmY3OWJiNDctMzhhOC00MTc2LWJmMzYtOGNiMGM3YWM0OTgwIiwiaWF0IjoxNzIwODA0MzU5LCJleHAiOjMzMjkxMzY0MzU5fQ.WcMTcZslDiQ0EJaLMeLlXaXq3OY45MmP5M9jFaAH3Oo "=394x")

The "Tutorials" category currently expands to show sub-pages, but we wish to disable its clickability while maintaining its role as a container.

### Describe alternatives you've considered

Direct Removal: Initially attempted to remove the link from the `sidebars.js` configuration for the "Tutorials" category, which resulted in build failures due to missing document associations.

Placeholder Document: Thought of linking "Tutorials" to a placeholder or minimal README document. However, this approach contradicts our goal of having a purely navigational, non-clickable category.

## Implementation Request

Seeking assistance in customizing the Docusaurus theme, specifically the sidebar component, to achieve a non-clickable "Tutorials" category. This customization should allow the category to remain interactive for revealing sub-pages without navigating away upon selection.

### Technical Details

* Swizzling: Open to exploring swizzling the sidebar component for deeper customization.
* Custom Scripting: Considered adding custom JavaScript to prevent default click actions on the "Tutorials" category link, though this approach may not be sustainable or align with best practices.

### Additional context

The documentation structure benefits significantly from having categories like "Tutorials" serve purely as organizational elements in the sidebar without contributing to the site's navigational paths. This adjustment enhances usability by clearly delineating between navigational labels and content pages.

**Comment by CryptoTotalWar** [comment]
Issue: when attempting to rename the Tutorials category label from "Tutorials" to "getting-started" we get the following error:
 
 docs: [
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'tutorials/README',
      },
      
      ```
      ERROR
window.gtag is not a function
TypeError: window.gtag is not a function
    at eval (webpack-internal:///./node_modules/@docusaurus/plugin-google-gtag/lib/gtag.js:17:8)
    ```

**Comment by CryptoTotalWar** [comment]
We're not going to deal with gtag issue for now. 

Ed is going to see if we can use swizzle to customize the sidebar for the `Tutorials` -> renamed to `Getting Started` category as described here: https://www.phind.com/search?cache=kamxtl44c79n54yy8gvv2yyt

If Not, he may just create a label to simulate the container for getting started documentation pages.

**Comment by CryptoTotalWar** [comment]
We were able to achieve the desired results. 

We were also able to add another sidebar item for the docs' entry page. 

We're just missing to update the gtag information that is prompting warnings in development

**Comment by CryptoTotalWar** [comment]
https://github.com/MatrixAI/polykey.com/pull/45

This PR from Wen seems to reference implementation details with GTAG....

However, unsure if it is relecant to our error 

```
window.gtag is not a function
TypeError: window.gtag is not a function
    at eval (webpack-internal:///./node_modules/@docusaurus/plugin-google-gtag/lib/gtag.js:17:8)
    ```

**Comment by CryptoTotalWar** [comment]
I don't think the error we are receiving above is related to any changes we made with our directory structure... 

We're just going to have to make a separate ticket to investigate this problem and have Ed look into to try to fix.
